Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\cunss\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "destuff.py", line 168, in checkbox_click
    self.previous_search_click()
  File "destuff.py", line 293, in previous_search_click
    self.search(search_term)
  File "destuff.py", line 197, in search
    self.var_case_sensitive.get(), self.var_regex.get()
  File "C:\Projects\DeStuff\utils.py", line 14, in wrapper
    result = func(*args, **kwargs)
  File "C:\Projects\DeStuff\utils.py", line 149, in find
    if search_term in temp_line:
UnboundLocalError: local variable 'temp_line' referenced before assignment
function: find() executed in 0.08 seconds
function: find() executed in 0.09 seconds
function: find() executed in 0.09 seconds
function: find() executed in 0.08 seconds
function: find() executed in 0.08 seconds
function: find() executed in 0.08 seconds